# Generated by Django 5.0.6 on 2024-12-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_feedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookTable',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Image',
        ),
    ]
