# Generated by Django 5.0.6 on 2024-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0011_order_delete_booktable_remove_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
