# Generated by Django 5.0.6 on 2024-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
