# Generated by Django 5.0.6 on 2024-12-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_alter_feedback_rating_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
